import { useTranslations } from 'next-intl';

export default function TermsOfService() {
    const t = useTranslations('Footer');

    return (
        <div className="min-h-screen bg-brand-bg text-white py-24 px-6 md:px-12 relative overflow-hidden">
            <div className="absolute top-0 right-1/4 w-[50%] h-[300px] bg-brand-secondary/10 blur-[120px] rounded-full mix-blend-screen pointer-events-none" />

            <div className="max-w-4xl mx-auto relative z-10">
                <header className="mb-12">
                    <h1 className="text-4xl md:text-5xl font-black mb-4 tracking-tight">{t('terms')}</h1>
                    <p className="text-slate-400 text-lg">
                        Effective Date: February 28, 2026
                    </p>
                </header>

                <div className="prose prose-invert prose-slate max-w-none">
                    <section className="mb-12">
                        <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">1. Open Source & MIT License</h2>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            AI Agent Flow is free, open-source software. The core framework and CLI are licensed under the <strong>MIT License</strong>.
                        </p>
                        <p className="text-slate-400 leading-relaxed italic">
                            Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files, to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software...
                        </p>
                    </section>

                    <section className="mb-12">
                        <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">2. Use of Service</h2>
                        <p className="text-slate-400 leading-relaxed mb-4">
                            By using AI Agent Flow, you agree to:
                        </p>
                        <ul className="list-disc list-inside text-slate-400 space-y-2 ml-4">
                            <li>Not use the tool for malicious purposes, including but not limited to creating malware or automated phishing systems.</li>
                            <li>Assume full responsibility for the code generated by the AI agents.</li>
                            <li>Comply with the Terms of Service of any third-party AI model providers you configure.</li>
                        </ul>
                    </section>

                    <section className="mb-12">
                        <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">3. Disclaimers: &quot;AS IS&quot;</h2>
                        <p className="text-slate-400 leading-relaxed">
                            AI AGENT FLOW IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.
                            THE AUTHORS OR COPYRIGHT HOLDERS SHALL NOT BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
                            WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
                            WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
                        </p>
                    </section>

                    <section className="mb-12">
                        <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">4. AI-Generated Content</h2>
                        <p className="text-slate-400 leading-relaxed">
                            You acknowledge that the content generated by AI Agent Flow (code, documentation, tests) is the output of probabilistic models.
                            It may contain bugs, security vulnerabilities, or logic errors. <strong>Always review and test all AI-generated code before deployment.</strong>
                        </p>
                    </section>

                    <section className="mb-12">
                        <h2 className="text-2xl font-bold mb-4 text-white border-b border-white/10 pb-2">5. Updates to Terms</h2>
                        <p className="text-slate-400 leading-relaxed">
                            As an evolving open-source project, we may update these terms from time to time.
                            Significant changes will be noted on this page and in the repository&apos;s main documentation.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
